name: C++ CI

on: [push]

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: mkdir build &&  cd build && cmake ../
    - name: make
      run: cd build && make
    - name: test
      run: cd build && ./doq_tests
    
  macos:
    name: macOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: mkdir build &&  cd build && cmake ../
    - name: make
      run: cd build && make
    - name: test
      run: cd build && ./doq_tests
